# Generated by Django 4.2.24 on 2025-10-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Вид оплаты')),
            ],
            options={
                'verbose_name': 'Вид оплаты',
                'verbose_name_plural': 'Виды оплаты',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Роль сотрудника')),
                ('params_one', models.BooleanField(default=False, verbose_name='Доход с услуг')),
                ('params_two', models.BooleanField(default=False, verbose_name='Доход с товара')),
                ('params_fre', models.BooleanField(default=False, verbose_name='Учитывание в истории')),
                ('params_data', models.BooleanField(default=False, verbose_name='Продление смены')),
                ('maney', models.PositiveSmallIntegerField(default=0, verbose_name='% с дохода')),
                ('maney_a', models.PositiveSmallIntegerField(default=0, verbose_name='% при оказании усдуги админом/барменом')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Вид - товар/услуга/спец услуга')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='Whom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Кому оказывалась услуга')),
            ],
            options={
                'verbose_name': 'Кому оказана услуга',
                'verbose_name_plural': 'Кому оказана услуга',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание смены')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная смена')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_as_admin', to='blog.personal', verbose_name='Администратор')),
                ('barman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_as_barman', to='blog.personal', verbose_name='Бармен')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.services', verbose_name='Вид услуги/товара')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.role', verbose_name='Роль сотрудника'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maney', models.PositiveSmallIntegerField(default=0, verbose_name='Оплата')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('ais', models.BooleanField(default=True, verbose_name='Закрыты/открыты записи')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.payment', verbose_name='Вид оплаты')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.personal', verbose_name='Исполнитель')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.service', verbose_name='Вид услуги/товара')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.services', verbose_name='Вид')),
                ('whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.whom', verbose_name='Кому оказывалась услуга')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
