# Generated by Django 4.2.24 on 2025-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='params_fre',
            field=models.BooleanField(default=False, verbose_name='Учитывание в истории'),
        ),
    ]
